export enum TableActionType {
    REQUEST_LIST = 'REQUEST_LIST',
    RECEIVE_LIST = 'RECEIVE_LIST',
    REQUEST_DESCR = 'REQUEST_DESCR',
    RECEIVE_DESCR = 'RECEIVE_DESCR',
    CHANGE_CURRENCY = 'CHANGE_CURRENCY',
    RECEIVE_CONVERT = 'RECEIVE_CONVERT',
    CLEAR_STATE = 'CLEAR_STATE',
}
